{% set name = "numpy_groupies" %}
{% set version = "0.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aed4afdad55e856b9e737fe4b4673c77e47c2f887c3663a18baaa200407c23e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - numpy_groupies
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ml31415/numpy-groupies
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Optimised tools for group-indexing operations: aggregated sum and more.'

extra:
  recipe-maintainers:
    - dcherian
    - ocefpaf
    - synapticarbors
    - ml31415
